### ISSUE TITLE
MongoDB.Driver now has Strong-Named Assemblies making this incompatible with recent versions of the driver

### ISSUE THREAD

**Issue by twiggins-cordel** [JordanDChappell/CSharp.Mongo.Migration#33]
Hello,

The recent releases of the MongoDB.Driver (2.27.0+) are Strong-Named Assemblies, which is causing incompatibilities with other libraries including the `AspNetCore.DataProtection.MongoDb` at version `7.0.0`.

I am not clear on the correct solution here, but I can see that `AspNetCore.DataProtection.MongoDb` now provides a 7.0.0 release which targets `MongoDB.Driver` version 2.28.0, and 8.0.0 which targets `MongoDB.Driver` version 3.0.0, I assume this is to allow users to choose either version of the MongoDB.Driver.

Similarly, the `AspNetCore.Identity.Mongo` package at version `9.0.0` is also targeting `MongoDB.Driver` version 2.28.0, since version `8.3.5` but are not providing a parallel version supporting `MongoDB.Driver` version 3.0.0.

**Comment by JordanDChappell** [comment]
This should be a fairly easy change for us to address in this library, as the only built dependency that we target is `MongoDB.Driver`. We may need to consider a major version increment if we update the version of the driver that we target to avoid breaking changes with consumers.

Something interesting about 'Strong-Named Assemblies' ([from Microsoft's documentation](https://learn.microsoft.com/en-us/dotnet/standard/assembly/strong-named#why-strong-name-your-assemblies)): 
> For .NET Core and .NET 5+, strong-named assemblies do not provide material benefits. The runtime never validates the strong-name signature, nor does it use the strong-name for assembly binding.

I wonder why the `MongoDB.Driver` project decided to go this way.

**Comment by JordanDChappell** [comment]
> This should be a fairly easy change for us to address in this library, as the only built dependency that we target is `MongoDB.Driver`. We may need to consider a major version increment if we update the version of the driver that we target to avoid breaking changes with consumers.
> 
> Something interesting about 'Strong-Named Assemblies' ([from Microsoft's documentation](https://learn.microsoft.com/en-us/dotnet/standard/assembly/strong-named#why-strong-name-your-assemblies)):
> 
> > For .NET Core and .NET 5+, strong-named assemblies do not provide material benefits. The runtime never validates the strong-name signature, nor does it use the strong-name for assembly binding.
> 
> I wonder why the `MongoDB.Driver` project decided to go this way.

Looks like a very small group of community members wanted this: https://jira.mongodb.org/browse/CSHARP-1276

**Comment by yoshifp** [comment]
Pull requests have been created which are intended to create 2 new versions of this `CSharp.Mongo.Migration` library which in the end will provide 3 major versions as options for library consumers.

Proposed versions are:
* `1.x` releases will remain with the current `MongoDB.Driver` library target version, and will never be updated to require 2.27.0+
* `2.x` releases will use the latest `2.27.0+` version that we can, being mindful of other libraries so users can upgrade libraries in tandem due to the `Strong-Named Assemblies` on the `MongoDB.Driver`.
* `3.x` releases will use the latest `3.0.0+` version that we can, being mindful of other libraries so users can upgrade libraries in tandem due to the `Strong-Named Assemblies` on the `MongoDB.Driver`.

Currently there will be no feature differences between them for the `CSharp.Mongo.Migration`, however I expect eventually that will change but has not been discussed at this point.

**Comment by JordanDChappell** [comment]
The branches listed above have been added to the default protected branch rule set.
